### ISSUE TITLE
`legacy` mode?

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Server#44]
This would be good for clients that wern't patched to support the new server.

**Comment by tnix100** [comment]
The server changes were done to make things more refined and have 1 good way of doing things instead of a bunch of ways (like with index having a bunch of different modes). Clients will just have to update, it's not that big of a change apart from indexes. All things that require an index (with the exception of ulist) will use mode 3 from now on (the same one that is used for home auto-get API.

As a side note if any client is still using `get_home` they should start using the REST API to get home posts.
